version: "3.8"
services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    environment:
      MYSQL_DATABAS: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=1234"]
      interval: 20s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    image: frontend:latest
    container_name: frontend
    # tty: true
    volumes:
      - ./frontend/main:/main/
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  # frontend:
  #   build: ./my-app
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./my-app:/app

  backend:
    build: ./backend
    # entrypoint: ./backend/entrypoint.sh
    image: backend:1.1.0
    container_name: backend
    restart: unless-stopped 
    environment: 
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/backend
    depends_on:
      mysql:
        condition: service_healthy
  
  redis: # hostname
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./reids_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin 
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "7878:80"
    depends_on:
      - mysql  



