version: "3.8"
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABAS: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=1234"]
      interval: 20s
      timeout: 5s
      retries: 3

  web:
    build: .
    entrypoint: ./entrypoint.sh
    image: backend:1.1.0
    restart: unless-stopped 
    environment: 
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

    ports:
      - "8787:8787"
    volumes:
      - ./backend:/backend
    depends_on:
      db:
        condition: service_healthy
  
  redis: # hostname
    image: redis:alpine
    command: redis-server --requirepass mitlabredis
    ports:
      - "6379:6379"
    volumes:
      - ./reids_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin 
    environment:
      PMA_HOST: db
    ports:
      - "7878:80"
    depends_on:
      - db  

  frontend:
    build: ./my-app
    image:
    environment:
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./my-app: