version: "3.8"
services:
  db:
    image: mysql:8.0.32
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mitlab
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=1234"]
      interval: 20s
      timeout: 5s
      retries: 3

  web:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/backend
    depends_on:
      db:
        condition: service_healthy
  