version: "3.8"
services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mitlab
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql_data:/var/lib/mysql
