# Generated by Django 4.2.1 on 2023-05-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30)),
                ('device_model', models.CharField(max_length=30)),
                ('device_sn', models.CharField(max_length=30)),
                ('device_id', models.CharField(max_length=30)),
                ('fw_version', models.CharField(max_length=30)),
                ('acc_amoount', models.CharField(max_length=30)),
                ('acc_feed_count', models.CharField(max_length=30)),
                ('acc_feed_time', models.CharField(max_length=30)),
                ('leak_info', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('ir_duty', models.IntegerField(max_length=30)),
                ('ir_range', models.IntegerField(max_length=30)),
                ('self_preserver', models.IntegerField(max_length=30)),
                ('sen_feed', models.IntegerField(max_length=30)),
                ('sen_stop', models.IntegerField(max_length=30)),
                ('power_save', models.IntegerField(max_length=30)),
                ('sol_time', models.IntegerField(max_length=30)),
                ('feed_time_on1', models.IntegerField(max_length=30)),
                ('feed_time_on2', models.IntegerField(max_length=30)),
                ('feed_time_on3', models.IntegerField(max_length=30)),
                ('amount_unit', models.IntegerField(max_length=30)),
                ('feed_limit', models.IntegerField(max_length=30)),
                ('amount_limit', models.IntegerField(max_length=30)),
                ('batt_warn', models.IntegerField(max_length=30)),
                ('batt_fail', models.IntegerField(max_length=30)),
                ('leak_det_period', models.IntegerField(max_length=30)),
                ('leak_det_keep', models.IntegerField(max_length=30)),
                ('leak_det_ontime', models.IntegerField(max_length=30)),
                ('leak_det_offtime', models.IntegerField(max_length=30)),
                ('report_auto', models.IntegerField(max_length=30)),
                ('update_auto', models.IntegerField(max_length=30)),
            ],
            options={
                'db_table': 'tap_devices_table',
            },
        ),
    ]
