# Generated by Django 4.2.1 on 2023-05-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='batt_fail',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='batt_warn',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='leak_det_keep',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='leak_det_offtime',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='leak_det_ontime',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='leak_det_period',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='report_auto',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='update_auto',
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='amount_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='amount_unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='feed_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='feed_time_on1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='feed_time_on2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='feed_time_on3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='ir_duty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='ir_range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='power_save',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='self_preserver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='sen_feed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='sen_stop',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='sol_time',
            field=models.IntegerField(),
        ),
    ]
