# Generated by Django 4.2.1 on 2023-05-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devicemodel_amount_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='amount_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='amount_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='feed_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='feed_time_on1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='feed_time_on2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='feed_time_on3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='ir_duty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='ir_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='power_save',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='self_preserver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='sen_feed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='sen_stop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='sol_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
