# Generated by Django 4.2.1 on 2023-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_devicemodel_amount_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
