# Generated by Django 4.2 on 2023-04-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
