# Generated by Django 4.2.1 on 2023-05-14 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RpiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpi_ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('rpi_name', models.CharField(blank=True, max_length=30, null=True)),
                ('rpi_location', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'device_rpi_table',
            },
        ),
        migrations.CreateModel(
            name='TapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30)),
                ('device_model', models.CharField(max_length=30)),
                ('device_sn', models.CharField(max_length=30)),
                ('device_id', models.CharField(max_length=30)),
                ('fw_version', models.CharField(max_length=30)),
                ('acc_amount', models.CharField(max_length=30)),
                ('acc_feed_count', models.CharField(max_length=30)),
                ('acc_feed_time', models.CharField(max_length=30)),
                ('leak_info', models.CharField(max_length=30)),
                ('ir_duty', models.PositiveIntegerField(default=1)),
                ('ir_range', models.PositiveSmallIntegerField(default=30)),
                ('self_preserver', models.PositiveIntegerField(default=1)),
                ('sen_feed', models.PositiveIntegerField(default=1)),
                ('sen_stop', models.PositiveIntegerField(default=1)),
                ('power_save', models.IntegerField(default=-1)),
                ('sol_time', models.PositiveIntegerField(default=30)),
                ('feed_time_on1', models.SmallIntegerField(default=-1)),
                ('feed_time_on2', models.SmallIntegerField(default=-1)),
                ('feed_time_on3', models.SmallIntegerField(default=-1)),
                ('feed_time_off1', models.SmallIntegerField(default=-1)),
                ('feed_time_off2', models.SmallIntegerField(default=-1)),
                ('feed_time_off3', models.SmallIntegerField(default=-1)),
                ('amount_unit', models.BooleanField(default=True)),
                ('feed_limit', models.BigIntegerField(default=-1)),
                ('amount_limit', models.IntegerField(default=-1)),
                ('batt_warn', models.SmallIntegerField(default=-1)),
                ('batt_fail', models.SmallIntegerField(default=-1)),
                ('leak_det_period', models.IntegerField(default=-1)),
                ('leak_det_keep', models.IntegerField(default=-1)),
                ('leak_det_ontime', models.SmallIntegerField(default=-1)),
                ('leak_det_offtime', models.SmallIntegerField(default=-1)),
                ('report_auto', models.CharField(default=-1, max_length=15)),
                ('update_auto', models.SmallIntegerField(default=-1)),
                ('rpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.rpimodel')),
            ],
            options={
                'db_table': 'device_rpi_tap_table',
            },
        ),
    ]
